### ISSUE TITLE
CSS基础测试1

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#1]
题目如下：
<img src="https://qidian.qpic.cn/qidian_common/349573/fa532d86e92770316aaced451874a2b1/0">

回答直接评论方式直接提交源码，我会统一整理，在周六进行点评和答疑。

**Comment by LonlyHeart** [comment]
`dl {
      display: flex;
      flex-wrap: wrap;
}
dt, dd {
      width: 50%;
      overflow: hidden;
      margin: 0;
}`

**Comment by uustoboy** [comment]
* { padding: 0; margin: 0; }
dl { border: 1px solid #999; padding: 10px; font-size: 14px; line-height: 20px; color: #999; width: 500px; overflow: hidden; }
dl dt { float: left; width: 50%; }
dl dd { float: right; width: 50%; text-align: right; }

**Comment by pizijun** [comment]
```css
dl {
  margin: 0
}

dt {
  float: left;
  clear: both;
}

dd {
  float: right;
}
```

**Comment by NatsumeF** [comment]
`<style>
    dl{
        width:400px;
        border:1px solid #eee;
    }
    dl::after{
        content: ""; 
        display: block;
        clear: both;
        visibility: hidden; 
    }
    dl dd{
        margin-left:0;
    }
    dl dt,dl dd{
        width:50%;
        padding:5px 10px;
        box-sizing: border-box;
    }
    dl dt{
        float:left;
    }
    dl dd{
        float:right;
        text-align: right;
    }
</style>
<dl>
    <dt>手机系统</dt>
    <dd>Android</dd>
    <dt>登录方式</dt>
    <dd>qq互联登录</dd>
    <dt>绑定时间</dt>
    <dd>1970-1-1</dd>
    <dt>绑定状态</dt>
    <dd>有效</dd>
</dl>`

**Comment by Xujkstra** [comment]
```css
dt {
  float: right;
}
```

**Comment by wotanjie** [comment]
`dl{
  width: 400px;
  border: 1px solid;
  display: flex;
  flex-wrap: wrap;
  padding: 10px
}
dt,dd{
  width: 50%;
}
dd{
  margin: 0;
  text-align:right;
}`

**Comment by WWR1234567** [comment]
dl {
    font-size: 0;
  }
  dt, dd {
    display: inline-block;
    width: 50%;
    margin-inline-start: 0;
    font-size: 12px;
  }
  dd {
    text-align: right;
  }

**Comment by Haloook** [comment]
`dl{
		width: 50%;
		border: 1px solid #eee;
		margin: 0 auto;
		padding: 20px 20px 0 20px;
		overflow: hidden;
		color: gray;
	}
	dt,dd{
		width: 50%;
		margin-bottom: 20px;
	}
	dt{
		float: left;
	}
	dd{
		float: right;
		text-align: right;

	} `

**Comment by Haloook** [comment]
`
<style>
	*{
		margin: 0;
		padding: 0;
	}
	dl{
		width: 50%;
		border: 1px solid #eee;
		margin: 0 auto;
		padding: 20px 20px 0 20px;
		overflow: hidden;
		color: gray;
	}
	dt, dd{
		width: 50%;
		margin-bottom: 20px;
	}
	dt{
		float: left;
	}
	dd{
		float: right;
		text-align: right;
	} 
	</style>
`

**Comment by Haloook** [comment]
`
<style>
	*{
		margin: 0;
		padding: 0;
	}
	dl{
		width: 50%;
		border: 1px solid #eee;
		margin: 0 auto;
		padding: 20px 20px 0 20px;
		overflow: hidden;
		color: gray;
	}
	dt, dd{
		width: 50%;
		margin-bottom: 20px;
	}
	dt{
		float: left;
	}
	dd{
		float: right;
		text-align: right;
	} 
	</style>
`

**Comment by masonzz** [comment]
```css
dl {
    padding: 5px;
    border: 1px solid #999;
    font-size: 0;
}

dt, dd {
    display: inline-block;
    width: 50%;
    font-size: 12px;
}

dd {
    margin-inline-start: 0;
    text-align: right;
}
```
不过这种实现在 dl 容器宽度不够时，会产生文字换行。

**Comment by qza6268963** [comment]
div{
      text-align: right;
      width: 300px;
      padding: 10px;
      border:1px solid #ccc;
    }
    dt{
      float: left;
    }

**Comment by woyaohaohaoxuexi** [comment]
dl {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            padding:  3%;
            border: 1px solid #d7d7d7;
        }
        dt {
            width: 50%;
        }
        dd {
            width: 50%;
            text-align: right;
            margin: 0;
        }

**Comment by sissi1** [comment]
dl,dd{
            margin: 0px;
        }
        dl{
            width:50%;
            padding: 10px;
            border:2px solid #eae4e4;
            line-height: 30px;
        }
        dl:after{
                content: '';
                clear: both;
                display: block;
        }
        dt{
            float: left;
            clear: right;
        }
        dd{
            float: right;
        }

**Comment by AsyncGuo** [comment]
*{margin: 0;padding: 0;}
dl{
  display:flex;
  flex-wrap:wrap;
  min-width: 300px;
  border:1px solid #eee;
}
dd,dt{
  width: 50%;
}
dd{
  text-align: right;
}

**Comment by Yannfy** [comment]
dt{
            display: inline-block;
            width: 50%;
        }
       dd{
            display: inline-block;
            width: 100px;
            text-align: right;
        }

**Comment by huyeye3344** [comment]
dl{
display: grid;
grid-template-columns:auto 1fr;
}
dd{
text-align:right;
}

**Comment by XboxYan** [comment]
用浮动实现还算比较简洁吧
```css
dl{
    margin: 0;
    padding: 5px 10px;
    overflow: hidden;
    border: 1px solid #ccc;
    line-height: 2em;
}
dt{
    float: left;
    clear: left;
}
dd{
    float: right;
    clear: right;
}
```

**Comment by XXig** [comment]
`*{
		margin:0;
		padding: 0;
	}
	dl{
		border:1px solid;
		padding:10px;
		line-height: 2;
	}
   /*flex*/
	dl.one{
		padding:10px;
		line-height: 2;
		display: flex;
		flex-flow: row wrap;
	}
	.one dt,dd{
		width: 50%;
	}
	.one dd{
		text-align: right;
	}
   /*浮动*/
	dl.two dt{
		float: left;
	}
	dl.two dd{
		width: 100%;
		text-align: right;
	}`

**Comment by XXig** [comment]
*{
margin:0;
padding: 0;
}
dl{
border:1px solid;
padding:10px;
line-height: 2;
}
/flex/
dl.one{
padding:10px;
line-height: 2;
display: flex;
flex-flow: row wrap;
}
dl.one dt,dd{
width: 50%;
}
dl.one dd{
text-align: right;
}

/浮动/
dl.two dt{
float: left;
}
dl.two dd{
width: 100%;
text-align: right;
}

**Comment by whrice** [comment]
<style type="text/css">
    *{
        margin:0px;
        padding: 0px;
    }
       dl{
           border:1px solid black;
           width:560px;
           margin:20px auto;
           padding-left:35px;
           padding-top: 20px; 
       }
       dt{
           width:120px;
           height:25px;
       }
       dd{
           width:160px;
           height:25px;
           position:relative;
           top:-28px;
           left:360px;
           text-align: right;
       }
    </style>

**Comment by whrice** [comment]
<style type="text/css">
    *{
        margin:0px;
        padding: 0px;
    }
       dl{
           border:1px solid black;
           width:560px;
           margin:20px auto;
           padding-left:35px;
           padding-top: 20px; 
       }
       dt{
           width:120px;
           height:25px;
       }
       dd{
           width:160px;
           height:25px;
           position:relative;
           top:-28px;
           left:360px;
           text-align: right;
       }
    </style>

**Comment by whrice** [comment]
<style type="text/css">
    *{
        margin:0px;
        padding: 0px;
    }
       dl{
           border:1px solid black;
           width:560px;
           margin:20px auto;
           padding-left:35px;
           padding-top: 20px; 
       }
       dt{
           width:120px;
           height:25px;
       }
       dd{
           width:160px;
           height:25px;
           position:relative;
           top:-28px;
           left:360px;
           text-align: right;
       }
    </style>

**Comment by whrice** [comment]
*{

​        margin:0px;

​        padding: 0px;

​        }

​       dl{

​           border:1px solid black;

​           width:560px;

​           margin:20px auto;

​           padding-left:35px;

​           padding-top: 20px; 

​       }

​       dt{

​           width:120px;

​           height:25px;

​       }

​       dd{

​           width:160px;

​           height:25px;

​           position:relative;

​           top:-28px;

​           left:360px;

​           text-align: right;

​       }

**Comment by white500** [comment]
dl{
				width: 400px;
				border: 1px solid #ccc;
				padding:8px;
				margin: 10px 0 10px 10px;
			} 
			dl>dt{
				float: left;
				color: #666;
			}
			dl>dd{
				color: #999;
				text-align: right;
				margin-bottom: 8px;
			}

**Comment by lilinjuna** [comment]
dl {
            border: 1px solid gray;
            overflow: hidden;
        }
        dl dt {
            float: left;
            padding: 10px;
        }
        dl dd {
            padding: 10px;
            text-align: right;
        }

**Comment by kkfor** [comment]
```css
dl {
  padding: 10px;
  line-height: 2;
  border: 1px solid #eee;
  text-align: right;
}
dt {
  float: left;
}
```

**Comment by morecho** [comment]
dl {
    border: 1px #ccc solid;
    overflow: hidden;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    padding-left: 10px;
    padding-right: 10px;
    padding-bottom: 10px;
}

dl>dt,
dl>dd {
    width: 50%;
    margin: 10px 0 0 0;
}

dl>dd {
    text-align: right;
}

**Comment by maczyt** [comment]
``` css
dl {
  width: 300px;
  padding: 10px;
  border: 1px solid gray;
}
dt {
  float: left;
}
dd {
  text-align: right;
}
```

**Comment by GCGligoudan** [comment]
dl {
      display: inline-block;
      padding: 15px;
      border: 1px solid #000;
      text-align: right;
    }
    dt {
      float: left;
    }
    dd {
      margin-left: 150px;
    }

**Comment by daniyyer** [comment]
dt{
  float:left;

}
dd{
  text-align:right;

}
dd:after{
  display: table;
  content: " ";
  clear: both;
}

**Comment by tiantianliu** [comment]
`dl,dd,dt{`
		margin:0;
		padding:0;
	}
	
	dl{
		padding:10px;
		border:1px solid #ccc;
	}
	dl:before,dl:after{
		content:'';
		display:table;
	}
	dl:after{
		clear:both;
	}

	dt{
		float:left;
		text-align:left;
	}
	dd{
		float:right;
		text-align:right;
	}
	
	dt,dd{
		width:50%;
	}

**Comment by 634323580** [comment]
dt { position: absolute; }
dd {text-align: right; }

**Comment by jiang-rong** [comment]
dl{
		border: 1px solid #eee;
		padding: 8px 12px;
		margin: 10px;
	}
	dt{
		float: left;
		margin-right: 20px;
		padding: 7px 0px;
	}
	dd{
		display: table-cell;
		width: 20000px;
		text-align: right;
		word-break: break-all;
		padding: 7px 0;
	}

**Comment by fzero17** [comment]
<style>
   dl {
     border:1px solid #ccc;
     padding:8px;
     max-width: 400px;
   }
   dt {
     display:inline-block;
     width:50%;
   }
   dd {
     display:inline;
     margin:0;
     float:right;
   }
  </style>

**Comment by fzero17** [comment]
` <style>
   dl {
     border:1px solid #ccc;
     padding:8px;
     max-width: 400px;
   }
   dt {
     display:inline-block;
     width:50%;
   }
   dd {
     display:inline;
     margin:0;
     float:right;
   }
  </style>`

**Comment by fzero17** [comment]
<style>
   dl {
     border:1px solid #ccc;
     padding:8px;
     max-width: 400px;
   }
   dt {
     display:inline-block;
     width:50%;
   }
   dd {
     display:inline;
     margin:0;
     float:right;
   }
  </style>

**Comment by jiang-rong** [comment]
dl{
	border: 1px solid #eee;
	padding: 8px 12px;
	margin: 10px;
}
dt{
	float: left;
	margin-right: 20px;
	padding: 7px 0px;
}
dd{
	display: table-cell;
	width: 20000px;
//或者overflow:hidden也行
	text-align: right;
	word-break: break-all;
	padding: 7px 0;  //用padiding来撑开行之间的间距，不直接用line-height，假设dd字符过长变成几行，line-height会导致行高过稀，用margin的话，dt float垂直margin不会重叠，dd overflow的margin会重叠，不在一行上，而table-cell属性直接不支持margin
}

**Comment by main2018** [comment]
> dt { position: absolute; }
> dd {text-align: right; }
or > dt { float: left； }

**Comment by Fans-of-mine** [comment]
*{margin:0;padding:0;}
dl{width: 40%;margin:10% auto;border: 1px solid #ddd;display: table;content: '';padding:1%;}
dd,dt{width:49%;}
dt{line-height: 30px;float: left;}
dd{float: right;text-align: right;line-height: 30px;}

**Comment by vickey155** [comment]
dl,dt,dd{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            line-height: 40px;
            font-size: 14px;
        }
        dl{
            width: 600px;
            display: flex;
            display: -webkit-flex;
            flex-flow: row wrap;
            border:1px solid #ddd;
            
        }
        dl dt{
            width: 30%;
            padding: 0 10px;
        }
        dl dd{
            padding: 0 10px;
            width: 70%;
            text-align:right;
        }

**Comment by ChinaTonyPlus** [comment]
/*内容多时自动换行自适应页面*/
dl{
	overflow: hidden;
	padding:15px;
	border:1px solid #ddd;
}
dt{
	float: left;
}
dd{
	margin: 0 0 10px;
	padding-left: 5em;
	text-align: right;
}

**Comment by lvanboy** [comment]
`       dl{
           width: 30%;
           margin:0 35%;
           overflow: hidden;
           border: 1px solid #ccc;
           padding: 20px;
           box-shadow: 1px 1px 2px 1px #ccc;
           color:#666;
       }
        dt{
            float: left;
            padding:5px;
            clear:both;
        }
        dd{
            float:right;
        }`

**Comment by lvanboy** [comment]
```
       dl{
           width: 30%;
           margin:0 35%;
           overflow: hidden;
           border: 1px solid #ccc;
           padding: 20px;
           box-shadow: 1px 1px 2px 1px #ccc;
           color:#666;
       }
        dt{
            float: left;
            padding:5px;
            clear:both;
        }
        dd{
            float:right;
        }
````

**Comment by BruceYuj** [comment]
dl {
            border: 1px solid grey;
            padding: 0.5em;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        dt {
            flex-basis: 50%;
        }

**Comment by BruceYuj** [comment]
```
    dl {
            border: 1px solid grey;
            padding: 0.5em;
            display: flex;
            flex-wrap: wrap;
            align-items: center
        }
        dt {
            flex-basis: 50%;
        }
        dd {
            text-align: right;
            flex-basis:50%;
            margin: 0;
        }
```      
处理其中某一个item产生多行的box，仍保持相对的布局

**Comment by DFLovingWM** [comment]
给定的布局中，dt、dd都是块级元素、会分行，可以使用“二列布局”思路，分成两列，并且对右边使用text-align: right使其向右对齐。

```css
dt {
  float: left;
}

dd {
  overflow: hidden;
  text-align: right;
}
```

**Comment by zhangxinxu** [comment]
补充一个没有的：

```css
dl {
  border: 1px solid #ccc;
  background-color: #fff;
  padding: 10px;
  line-height: 1.5;
}
dd {
  text-align: right;
  margin: -1.5em 0 0 5em;
}
```

**Comment by zhenhappy** [comment]
今天直播的时候张老师在找一个flex版本的没找到, 我随意写了一个, 不知道这个效果是不是张老师想要的那个
```
dl {
  display: flex;
  flex-direction: column;
}
dt {
  width: 20%;
}
dd {
  margin-left: 0;
  max-width: 80%;
  text-align: right;
  align-self: flex-end;
  transform: translateY(-100%);
}
```

**Comment by whrice** [comment]
` *{

        margin:0px;

        padding: 0px;

        
}
   dl{
       border:1px solid black;
       width:560px;
       margin:20px auto;
       padding-left:35px;
       padding-top: 20px;
    
   }
   dt{

       width:120px;
       height:25px;
     
   }
   dd{
       width:160px;
       height:25px;
       position:relative;
       top:-28px;
       left:360px;
       text-align: right;
   }`

**Comment by whrice** [comment]
` *{

        margin:0px;

        padding: 0px;

        
}
   dl{
       border:1px solid black;
       width:560px;
       margin:20px auto;
       padding-left:35px;
       padding-top: 20px;
    
   }
   dt{

       width:120px;
       height:25px;
     
   }
   dd{
       width:160px;
       height:25px;
       position:relative;
       top:-28px;
       left:360px;
       text-align: right;
   }`

**Comment by whrice** [comment]
```css
 dl{
       border:1px solid black;
       width:560px;
       margin:20px auto;
       padding-left:35px;
       padding-top: 20px;
   }
```

**Comment by GITDengMing** [comment]
dl{
  display: flex;
  flex-wrap: wrap;
  border: 2px solid #aaa;
  padding:10px;
}
dd{
  margin:0;
  width: calc(100% - 100px);
  text-align:right;
  margin:10px 0;
}
dt{
  width:100px;
  margin:10px 0;
}

**Comment by chen-rongliang** [comment]
```
body,
dl,
dt,
dd {
    margin: 0
}

dl {
    line-height: 32px;
    width: 560px;
    text-indent: 16px;
    border: 1px solid #ccc;
}

dl>dd {
    margin-top: -32px;
    direction: rtl;
    color: #ccc;
}
```

**Comment by miaomiaolin** [comment]
dl,dt,dd { margin: 0 }
dl {
    width: 500px;
    padding: 1rem;
    line-height: 2;
    color: #777;
    border: 1px solid #777;
}
dl::after {
    content: '';
    display: block;
    clear: both;
}
dt {
    float: left;
    width: 50%;
}
dd {
    float: right;
}

**Comment by wingmeng** [comment]
``` css
dl {
    max-width: 400px;
    padding: 5px 15px;
    line-height: 2;
    box-sizing: border-box;
    border: 1px solid #ccc;
    box-shadow: 1px 1px 0 rgba(0,0,0,.15);
}

dt {display: inline;}

/* 灵感来自《CSS解密》P116 */
dd + dt::before {
    content: '\A';
    white-space: pre;
}

dd {
    float: right;
    margin: 0;
}
```

![demo min](https://user-images.githubusercontent.com/9009389/51232087-a8dc9180-19a0-11e9-97ea-bc2714e8cecb.png)

**Comment by Befend** [comment]
dt, dd {
  width: 50%;
  margin: 0;
  float: left;
}

**Comment by Befend** [comment]
dl{
  width: 400px;
  padding: 5px 10px;
  border: 1px solid #c1c1c1;
  overflow: hidden;
}
dt, dd {
  width: 50%;
  margin: 0;
  padding: 5px 0;
  float: left;
}
dd {
  text-align: right;
}

**Comment by Evoque** [comment]
**1. 笨方法：子元素宽度50%**
```css
dl {
    padding:10px;
    font-size: 0;
}
dt, dd {
   font-size: 14px;
   display: inline-block;
   width: 50%;
   margin-bottom: 10px;
}
dd {
   text-align:right;
   margin: 0;
}
```

**Comment by 821190452** [comment]
```
    //代码片段
    <style>
        html {
	    font-size: 16px;
	}
			
	body {
	    margin: 0;
	}
			
	.qiuzhi-box {
	    width: 300px;
	    margin: 1rem;
	    padding: 1rem;
				
	    border: 1px solid #CCCCCC;
	    box-sizing: border-box;
        }
			
	.qiuzhi-box::before,
	.qiuzhi-box::after {
	    content: '';
	    display: table;
	}
			
	.qiuzhi-box::after {
	    clear: both;
	}
			
	.qiuzhi-box dt,			
	.qiuzhi-box dd {
	    padding-bottom: .25rem;
	}
			
	.qiuzhi-box dt:last-child,			
	.qiuzhi-box dd:last-child {
	    padding-bottom: 0;
	}
			
	.qiuzhi-box dt {
	    float: left;
	    width: 25%;
	    text-align: left;
	}
			
	.qiuzhi-box dd {
	    float: right;
	    width: 75%;
	    margin: 0 auto;
	    text-align: right;
	}
    </style>
```

**Comment by y389278443z** [comment]
dl,dd{
            margin:0;
        }
        dl{
          width:500px;
          border :1px solid #e5e5e5;
          padding:0 20px;
        }
        dt{
            float:left;
            width:100px;
            margin-top:10px;
            color:#666;
        }
        dd{
            overflow: hidden;
            padding:10px 0;
            text-align: right;
        }

**Comment by y389278443z** [comment]
因为dd是text-align：right；  所以文字都是右对齐的，如果内容超过一行，也是右对齐的，有没有办法不超过一行的时候右对齐， 超过一行的话就左对齐。

**Comment by 0900304132** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style type="text/css">
    dl {
        font-size: 0;
        border: 1px solid #dedede;
        padding: 15px;
    }

    dd,
    dt {
        display: inline-block;
        width: 50%;
        margin: 0;
        font-size: 16px;
    }
    dt{
    	color: #b0b0b0;
    }

    dd {
        text-align: right;
    }
    </style>
</head>

<body>
    <dl>
        <dt>手机系统</dt>
        <dd>Android</dd>
        <dt>登录方式</dt>
        <dd>QQ 互联登录</dd>
        <dt>绑定时间</dt>
        <dd>2019-03-06 15:08:22</dd>
        <dt>绑定状态</dt>
        <dd>有效</dd>
    </dl>
</body>

</html>

**Comment by xjt31012** [comment]
```css
dl {
    display: flex;
    flex-wrap: wrap;
}
dt, dd{
    width: 50%;
    overflow: hidden;
    margin: 0;
}
```

**Comment by heiyantutu** [comment]
```css
dl{
    border: 1px solid #eee;
    display: flex;
    flex-wrap: wrap;
    padding: 20px;
}
dt,dd{
    width: 50%;
    overflow: hidden;
    margin: 0;
}
dd{
    text-align: right;
}
```

**Comment by yz-xlame** [comment]
dt {
  float: left;
  clear: both;
}

dd {
  float: right;
}

**Comment by zer0fire** [comment]
[Demo](https://jsbin.com/qagadadimo/1/edit?html,css,output)
```css
dl {
  border: 1px solid;
  padding: 10px;
}
dt,
dd {
  margin: 5px 0;
  width: 49%;
  display: inline-block;
}
dd {
  margin:0;
  text-align: right;
}

```
```html



```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <dl>
    <dt>手机系统</dt>
    <dd>Android</dd>
    <dt>登录方式</dt>
    <dd>QQ 互联登录</dd>
    <dt>绑定时间</dt>
    <dd>2019-09-02 11:10</dd>
    <dt>绑定状态</dt>
    <dd>有效</dd>
  </dl>
</body>
</html>

**Comment by Zhang998** [comment]
`dl{
      display: flex;
      flex-wrap: wrap;
    }
    dd{
      margin: 0;
      text-align: right;
      flex:70%;
    }
    dt{
      flex: 30%;
    }`

**Comment by Zhang998** [comment]
```css
dl{
      display: flex;
      flex-wrap: wrap;
    }
    dd{
      margin: 0;
      text-align: right;
      flex:70%;
    }
    dt{
      flex: 30%;
    }
```

**Comment by Zhang998** [comment]
```css
    dl{
      display: flex;
      flex-wrap: wrap;
    }
    dd{
      margin: 0;
      text-align: right;
      flex:70%;
    }
    dt{
      flex: 30%;
    }
```
