### ISSUE TITLE
~

### ISSUE THREAD

**Issue by Forx-Js** [zhangxinxu/quiz#17]
[DEMO](https://codepen.io/forx-js/pen/rbaBvo)
```html
  <div class="chat_box">
    <div class="chat_body">
      <ul class="chat_list">
        <li class="chat_item">
          <div class="chat_item_avatar"></div>
          <div class="chat_item_right">
            <div class="chat_item_niceName">我是昵称~</div>
            <div class="chat_item_text">我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称</div>
          </div>
        </li>
        <li is-me class="chat_item">
          <div class="chat_item_avatar"></div>
          <div class="chat_item_right">
            <div class="chat_item_niceName">我是昵称~</div>
            <div class="chat_item_text">我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称</div>
          </div>
        </li>
        <li is-me class="chat_item">
          <div class="chat_item_avatar"></div>
          <div class="chat_item_right">
            <div class="chat_item_niceName">我是昵称~</div>
            <div class="chat_item_text">我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称</div>
          </div>
        </li>
        <li class="chat_item">
          <div class="chat_item_avatar"></div>
          <div class="chat_item_right">
            <div class="chat_item_niceName">我是昵称~</div>
            <div class="chat_item_text">我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称</div>
          </div>
        </li>
        <li is-me class="chat_item">
          <div class="chat_item_avatar"></div>
          <div class="chat_item_right">
            <div class="chat_item_niceName">我是昵称~</div>
            <div class="chat_item_text">我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称我是昵称</div>
          </div>
        </li>
      </ul>
    </div>
  </div>
```
```css
body,
ul,
ol,
li {
  margin: 0;
  padding: 0;
  list-style: none;
}

* {
  box-sizing: content-box;
}

.chat_box, .chat_list {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
}

.chat_box {
  width: 400px;
  margin: 0 auto;
}

.chat_body {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 80%;
  top: 10%;
  bottom: 10%;
}

.chat_list {
  background: #fee;
  overflow-y: auto;
  padding: 8px 0;
}

.chat_item {
  border: 1px solid transparent;
  display: flex;
  flex-flow: row nowrap;
  justify-content: flex-start;
  align-items: flex-start;
}

.chat_item[is-me] {
  flex-direction: row-reverse;
}

.chat_item_avatar {
  flex: 0 0 50px;
  height: 50px;
  background-color: #fff;
  border-radius: 50%;
  margin: 25px 10px 0;
}

.chat_item_right {
  flex: 1;
}

.chat_item_niceName {
  font-size: 12px;
  line-height: 2.5;
  color: #bbb;
}

[is-me] .chat_item_niceName {
  color: #000;
  text-align: right;
}

.chat_item_text {
  position: relative;
  border-radius: 10px;
  color: #fff;
  font-size: 16.66667px;
  letter-spacing: 1.25px;
  padding: 1.66667px 10px;
  line-height: 2;
  margin: 0 10px 0;
}

.chat_item_text::before {
  content: '';
  position: absolute;
  display: block;
  top: 3px;
  width: 10px;
  height: 15px;
  border-style: solid;
  border-width: 7.5px 0 0 0;
}

.chat_item_text {
  background-color: #bbbbbb;
}

.chat_item_text::before {
  border-color: #bbbbbb;
  left: -8px;
  border-radius: 100% 0 0 0 /50%;
}

[is-me] .chat_item_text {
  background-color: #8cd1ec;
}

[is-me] .chat_item_text::before {
  border-color: #8cd1ec;
  right: -8px;
  left: unset;
  border-radius: 0 100% 0 0 /50%;
}
```
第一次玩这个,很多不熟悉,请指点!
