### ISSUE TITLE
CSS基础测试7

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#28]
本期题目如下：

<img src="https://qidian.qpic.cn/qidian_common/349573/69ec88d79b9a8f8761c7bbd6ee604843/0">

请附上对应的CSS代码，注意缩进和代码高亮，可以使用下面语法：

<pre>```css
你的代码在这里
```</pre>

**请提供在线的可访问的demo地址**（精力有限，没有demo减1分），如jsbin.com、jsfiddle.net或codepen.io，使用国内的类似工具也可以。

本周六是端午节，小测答疑推迟到下下周周六6月15日上午10:00，和JS小测33期一起答疑，直播地址：https://live.bilibili.com/21193211

首位答题者会额外2积分，同时会被翻牌。

感谢您的参与！

**Comment by yaeSakuras** [comment]
赶个第一
```css
html,body{
            height: 100%;
            padding: 0;
            margin: 0;
        }

        .container{
            display: flex;
            flex-direction: column;
            height: 100%;
        }
        .content{
            flex: 1 0 auto;
        }
        .footer{
            flex: 0 0 auto;
        }
```

**Comment by sghweb** [comment]
[demo](https://codepen.io/sghweb/pen/JqVqQJ)
```css
body {
  padding: 0;
  margin: 0;
}
.container {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  min-height: 100vh;
}
.footer {
  background: red;
}
```

**Comment by liyongleihf2006** [comment]
[jsbin](https://jsbin.com/dapokaloxu/edit?html,css,js,output)
```css
body{
    margin: 0;
}
.container{
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    height: 100vh;
    overflow-x:hidden;
    overflow-y:auto;
}
.content{
    background: lightblue;
}
.footer{
    background:lightcoral;
}
```

**Comment by wingmeng** [comment]
[> 在线 Demo <](https://codepen.io/wingmeng/pen/RmOmdy)

```css
body {margin: 0;}
main, content, footer {display: block;}

.container {
  display: flex;
  flex-flow: column;
  min-height: 100vh;  /* 不设置固定高度 */
}

.content {flex: 1;}

.footer {
  color: #fff;
  background: #555;
}
```

**Comment by jsweber** [comment]
[在线演示](http://js.jirengu.com/kegiq/1/edit)

```css
    body {
        margin: 0;
        font-size: 30px;
    }

    .container {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .content {
        background: #ccc;
        height: 300px;
    }

    .footer {
        background: yellow;
    }
```

**Comment by Seasonley** [comment]
# [🎴Demo](https://codepen.io/seasonley/pen/XwQQRx)
一般思路flex
```css
.container{
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  min-height: 100vh;
}
```

如果标签里只有纯文本，可以用 table系列
```css
.container{
  display: table;
  height:100vh;
}
.footer{
  display: table-footer-group;
}
```
```css
.container{
  display: table;
  height:100vh;
}
.content{
  display: table-row;
}
.footer{
  display: table-cell;
  vertical-align:bottom;
}
```

**Comment by sanshiliuxiao** [comment]
**[Demo](https://codepen.io/xiaoheierhao/pen/xNNgyW)**
```html
<div class="container">
  <div class="content">
    <div class="ctx">内容块</div>
  </div>
  <div class="footer">底部</div>
</div>
```
```css
html, body {
  height: 100%;
  padding: 0;
  margin: 0;
}
.container {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.content {
  flex: 1;
}
.ctx {
  /*内容不满一屏*/
  height: 100px;
  /*内容 超过一屏*/
  /*
  height: calc(100vh + 300px);
  */
  background: yellow;
}

.footer {
  height: 100px;
  background: #ccc;
}
```

**Comment by YuanChaobo** [comment]
``html,body{
			margin:0;
			min-height: 100%;
		}
		html{
			position: relative;

		}
		.content{
			display: block;
			height: 10vh;
		}
		.footer{
			position: absolute;
			left: 0px;
			bottom: 0px;
			width: 100%;
			height: 40px;
			background: blue;
		}``

**Comment by YuanChaobo** [comment]
`html,body{
		margin:0;
		min-height: 100%;
}
html{
	position: relative;
}
.content{
		display: block;
		height: 10vh;
}
.footer{
		position: absolute;
		left: 0px;
		bottom: 0px;
		width: 100%;
		height: 40px;
		background: blue;
}`

**Comment by YuanChaobo** [comment]
`html,body{
	margin:0;
	min-height: 100%;
}
html{
	position: relative;

}
.content{
	display: block;
	height: 10vh;
}
.footer{
	position: absolute;
	left: 0px;
	bottom: 0px;
	width: 100%;
	height: 40px;
	background: blue;
}`

**Comment by YuanChaobo** [comment]
`	html,body{
		margin:0;
		min-height: 100%;
	}
	html{
		position: relative;

	}
	.content{
		display: block;
		height: 10vh;
	}
	.footer{
		position: absolute;
		left: 0px;
		bottom: 0px;
		width: 100%;
		height: 40px;
		background: blue;
	}`

**Comment by YuanChaobo** [comment]
[demo](https://codepen.io/yuanchaobo/pen/ZNNyoL?editors=1100)

	html,body{
		margin:0;
		min-height: 100%;
	}
	html{
		position: relative;
	}
	.content{
		display: block;
		height: 10vh;
	}
	.footer{
		position: absolute;
		left: 0px;
		bottom: 0px;
		width: 100%;
		height: 40px;
		background: blue;
	}

**Comment by NeilC1991** [comment]
Flex
https://codepen.io/crazyboy/pen/zQQroJ
```css
.container {
	display: flex;
	flex-direction: column;
	min-height: 100vh;
}
.content {
	flex: 1;
}
```

其他
https://codepen.io/crazyboy/pen/OYYjzR
```css
.container {
	position: relative;
	/*暂时想不到省略这里尺寸的方法*/
	--footerheight: 100px; 
}
.content {
	display: block;
	min-height: calc(100vh - var(--footerheight));
	padding-bottom: var(--footerheight);
}
.footer {
	height: var(--footerheight);
	position: absolute;
	bottom: 0;
}
```

**Comment by smileyby** [comment]
[在线DEMO](https://codepen.io/smileyby/pen/EzzXdo)

> 多放了一个盒子`<div class="push"></div>`，来抵消margin的负值，在内容少的时候不会覆盖在内容上
```css
body, html {
  height: 100vh;
  margin: 0;
}
.content {
  display: block;
  min-height: 100vh;
  margin: 0 auto -50px;
  background-color: #E9EEF3;
}
.footer, .push {
  min-height: 50px;
}
.footer {
  background-color: lightblue;
}
```

**Comment by JaimeCheng** [comment]
[demo](https://jsbin.com/wepojobabo/edit?html,css,output)
```css
body,html {
      min-height: 100vh;
      box-sizing: border-box;
      margin: 0;
    }
    .container {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }
    .content, .footer {
      border: 1px solid red;
    }
```

**Comment by brenner8023** [comment]
[在线demo](https://codepen.io/brenner8023/pen/pmmdLy)
```css
html, body {
  height: 100%;
  margin: 0;
}
.container {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.content {
  width: 100px;
  height: 100px;
  background-color: red;
}
.footer {
  width: 200px;
  height: 100px;
  background-color: green;
}
```

**Comment by ximuli** [comment]
[在线地址](http://js.jirengu.com/sivetuwura/1/edit?html,css,output)
flex 布局
```css
body { margin: 0; }
.container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.content {
  /* height: 1000px; */
  /* height: 500px; */
  /* height: 1200px; */
  flex-shrink: 0;
  background-color: lightgreen;
}
.footer {
  background-color: lightblue;
}
```

**Comment by XboxYan** [comment]
[demo](https://codepen.io/xboxyan/pen/gJJxqL)

```css
html,body{
    height: 100%;
    margin: 0;
}
.container {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: auto;
}
.content {
    flex: 1;
}
```

如果高度是固定的，下面兼容性更好
```css
html,body{
    height: 100%;
    margin: 0;
}
.container {
    height: 100%;
    overflow: auto;
}
.content {
    box-sizing:border-box;
    min-height: 100%;
    padding-bottom:100px;
}
.footer{
   height:100px;
   margin-top:-100px;
}
```

**Comment by AsyncGuo** [comment]
[demo](https://codepen.io/anon/pen/arrqXZ)
```css
html, body{
  margin: 0;
  height: 100%;
}
.container{
  display: flex;
  flex-direction: column;
  min-height: 100%;
}
.content{
  flex: 1;
}

```

**Comment by a694750795** [comment]
html,
        body {
            margin: 0;
            padding: 0;
        }

        .container {
            position: relative;
            min-height: 100vh;
            display: block;
            padding-bottom: 30px;
            box-sizing: border-box;
        }

        .footer {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            line-height: 30px;
        }

**Comment by frankyeyq** [comment]
[demo](https://codepen.io/anon/pen/qGGYWM)
```css
html,body {
    margin: 0;
}
.container {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}
```

**Comment by Forx-Js** [comment]
A PEN BY [Forx-Js](https://codepen.io/forx-js/pen/NVVYmG?editors=1100)
适当的加了加`pading`和`background`
```css
.container{
  position:absolute;
  top:0;
  left:0;
  right:0;
  bottom:0;
  display:flex;
  flex-flow:column nowrap;
}
.content{
  flex:1 0;
}
.footer{
  flex:0 0;
  background:#333;
  padding:8px 12px;
  color:#fff
}
```

**Comment by tzmy** [comment]
[在线demo](https://codepen.io/tzmy/pen/vwwrZx)
```css
body,html{
            margin: 0;
            padding: 0;
            height: 100%;
        }
        .container{
            display: flex;
            flex-flow: column;
            justify-content: space-between;
            min-height: 100%;
            background: #2c94e9;
        }
        .content{
            display: block;
            background: #dedede;
        }
        .footer{
            display: block;
            background: #d6c915;
        }
```
```html
<content class="content">
            内容
            <div style="height: 400px;"></div>
            <!--<div style="height: 800px;"></div>-->
            内容end
        </content>
        <footer class="footer">
            底部start
            <div style="height: 200px;"></div>
            底部
        </footer>
```

**Comment by livetune** [comment]
[demo codepen](https://codepen.io/livetune/pen/EzzBYy?editors=1100)
```css
/* 自适应 */
.container {
  width: 300px;
  height: 500px;
  margin: 20px;
  overflow-y: scroll;
  background: #ececec;
  display: flex;
  flex-direction: column;
}
.container .footer {
  background: red;
  flex: 0;
}
.container .content {
  background: green;
  flex: 1;
}
/* 固定高度 */
.container1 {
  width: 300px;
  height: 500px;
  margin: 20px;
  overflow-y: scroll;
  background: #ececec;
}

.container1 .content {
  display: block;
  background: green;
  min-height: calc(100% - 100px);
}
.container1 .footer {
  height: 100px;
  background: red;
}
```

**Comment by qianfengg** [comment]
[demo](https://jsbin.com/livuneb/edit?html,css,output)
```html
    <main class="container">
        <content class="content">
            内容
        </content>
        <footer class="footer">底部</footer>
    </main>
```
```css
        body{
            margin: 0;
        }
        .container{
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        .content{
            flex: 1 0 auto;
        }
        .footer{
            flex: 0 0 auto;
            background-color: skyblue;
        }
```

**Comment by CandyQiu** [comment]
[demo is here~](https://codepen.io/CandyQiu/pen/rgEpaw?editors=1100)

感觉是水印效果~用flex最快~

```css

.container{
  display:flex;
  flex-direction: column;
  min-height: 100%;
  justify-content: space-between;
}

```

**Comment by Despair-lj** [comment]
[demo](https://codepen.io/despair-lj/pen/YbmKoZ)
```css
body,
html {
  height: 100%;
}
body {
  margin: 0;
}
.container {
  display: flex;
  min-height: 100%;
  flex-direction: column;
  justify-content: space-between;
}
.footer {
  min-height: 30px;
  background: orange;
}
```
# 
一开始的思路是饿了么弹框那种 margin-top 为负数的 css 效果，但是考虑到需要修改 dom 以及 footer 的高度不为固定，所以该方法无法符合题目要求
```css
body,
html {
  height: 100%;
}
body {
  margin: 0;
}
.container-another {
  overflow: auto;
  height: 100%;
  background-color: #fff;
}
.content-wrapper {
  padding-bottom: 30px;
}
.content {
  display: block;
  min-height: 100%;
}
.footer {
  min-height: 30px;
  text-align: center;
  margin: -30px auto 0;
  background-color: orange;
}
```

**Comment by tao1874** [comment]
```css
 html,body {
        height: 100%;
        margin: 0;
      }
      .container{
          height: 100%;
          display: grid;
          grid-template-rows: 1fr auto;
      }
      .footer {
          background-color: red;
      }
```
[Demo](https://codepen.io/tao1874/pen/YoKgaZ)

**Comment by ziyingjie** [comment]
[demo](https://codepen.io/ziyingjie/pen/WqNEYN)


    html,
    body {
        padding: 0;
        margin: 0;
    }

    .container {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
    }

    footer {
        height: 100px;
        background: pink;
        margin-top: auto;
    }

**Comment by mengxiaoixao** [comment]
地址：https://codepen.io/mengxiaoixao/pen/mvzwOO
```css
.content{
  min-height:100vh;
  background:red;
  display: grid;
  align-content: space-between;
}
footer{
  background:green;
}

```
