### ISSUE TITLE
CSS基础测试8

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#31]
本期题目如下：

<img src="https://qidian.qpic.cn/qidian_common/349573/c9b403f5a46482ca6694eb9b834ef6aa/0">

请附上对应的CSS代码，注意缩进和代码高亮，可以使用下面语法：

<pre>```css
你的代码在这里
```</pre>

**请提供在线的可访问的demo地址**（精力有限，没有demo减1分），如jsbin.com、jsfiddle.net或codepen.io，使用国内的类似工具也可以。

本次小测为上学期最后一期小测，直播答疑本周六6月29日上午10:00 。我还在思考该给前几名奖励什么礼品。

直播地址：https://live.bilibili.com/21193211

首位答题者会额外2积分，同时会被翻牌。

感谢您的参与！

**Comment by wingmeng** [comment]
```css
.btn-group {
  display: grid;
  grid-gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(0, 1fr));
}
.btn-group + .btn-group {margin-top: 15px;}
.btn {
  flex: 1;
  padding: 6px 0;
  text-align: center;
  color: #666;
  background: transparent;
  border: 1px solid;
  border-radius: 10em;
}
.btn-danger {
  color: #ef7077;
}
```

```html
<div class="btn-group">
  <button class="btn btn-danger">按钮</button>
</div>
<div class="btn-group">
  <button class="btn btn-danger">按钮</button>
  <button class="btn btn-danger">按钮</button>
</div>
<div class="btn-group">
  <button class="btn btn-danger">按钮</button>
  <button class="btn btn-danger">按钮</button>
  <button class="btn btn-danger">按钮</button>
</div>
```

**Comment by ThoughtZer** [comment]
```css
       * {
            padding: 0;
            margin: 0;
        }
        .wrapper {
            height: 100px;
            padding: 25px 1rem;
            display: flex;
            justify-content: space-between;
        }

        .wrapper > div {
            flex: 1;
            border-radius: 25px;
            height: 50px;
            line-height: 50px;
            text-align: center;
            border: 1px solid red;
            margin-right: 1rem;
        }

        .wrapper > div:last-child {
            margin-right: 0;
        }
```
```html
    <div class="wrapper">
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
        <div>按钮</div>
    </div>
```

**Comment by Tenwq** [comment]
```css
.btn-group{
	display: flex;
	padding: 1rem .5rem;
	justify-content: space-between;
}
.btn{
	flex: 1;
	height: 30px;
	border: 1px solid #ef7b82;
	color: #ef7b82;
	font-size: 14px;
	border-radius: 30px;
	background-color: transparent;
	box-shadow: 0 0 1px #ef7b82;
	padding: 0;
	margin: 0 .5rem;
}
```
```html
<div class="btn-group">
	<button type="button" class="btn">按钮</button>
</div>
<div class="btn-group">
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
</div>
<div class="btn-group">
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
</div>
<div class="btn-group">
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
	<button type="button" class="btn">按钮</button>
</div>
```

**Comment by bugaosunihhh** [comment]
```less
.wrapper{
  display:flex;
  flex-wrap: nowrap;
  margin-bottom: 4em;
  .btn{
    flex:1;
    margin-right:1rem;
    box-sizing:border-box;
    border-radius: 1em;
    border: 1px solid currentColor;
    text-align:center;
    color: pink;
    line-height: 2em;
    &:last-child{
      margin-right:0
    }
  }
}
```

```html
<div class="wrapper">
  <div class="btn">按钮</div>
</div>

<div class="wrapper">
  <div class="btn">按钮</div>
  <div class="btn">按钮</div>
</div>

<div class="wrapper">
  <div class="btn">按钮</div>
  <div class="btn">按钮</div>
  <div class="btn">按钮</div>
</div>
```

**Comment by yaeSakuras** [comment]
```css
.container {
    background: #f6f7f9;
}

.btn-group {
    display: flex;
    padding: 1rem;
}

[class|='ui-btn'] {
    flex: 1;
    margin-right: 1rem;
    background: transparent;
    border: 1px solid;
    padding: 1em;
    border-radius: 10em;
}

.btn-group > [class|='ui-btn']:last-child {
    margin-right: 0;
}
[class*='-red']{
    color: #ef7077;
}
[class*='-blue']{
    color: skyblue;
}
```
```html
<div class="container">
    <div class="btn-group">
        <button class="ui-btn-red">按钮</button>
        <button class="ui-btn-red">按钮</button>
        <button class="ui-btn-blue">按钮</button>
        <button class="ui-btn-blue">按钮</button>
    </div>
</div>
```

**Comment by Seasonley** [comment]
[demo](https://codepen.io/seasonley/pen/LKzZbQ?editors=1100)
```html
<div class="button-group">
  <a tabindex="0" role="button" class="button">按钮</a>
</div>
<div class="button-group">
  <a tabindex="0" role="button" class="button">按钮</a>
  <a tabindex="0" role="button" class="button">按钮</a>
</div>
<div class="button-group">
  <a tabindex="0" role="button" class="button">按钮</a>
  <a tabindex="0" role="button" class="button">按钮</a>
  <a tabindex="0" role="button" class="button">按钮</a>
</div>
```
```css
.button-group{
  font-size:0;
  display:flex;
  padding:0 0.5rem;
}
.button{
  flex:auto;
  font-size:1rem;
  color:#ef7077;
  position: relative;
  height: 2em;
  line-height:2em;
  min-width:4em;
  text-align:center;
  margin:0.5rem;
} 
.button::after{
  content: ''; 
  position: absolute;
  top: 0; 
  left: 0;
  border: 2px solid #ef7077;
  box-sizing: border-box;
  border-radius:2em;
  width: 200%;
  height: 200%;
  transform: scale(0.5);
  transform-origin: left top;
}
```

**Comment by liyongleihf2006** [comment]
[jsbin](https://jsbin.com/hofexuc/edit?html,css,output)

```css
.average-button-group {
  display: table;
  table-layout: fixed;
  text-align: center;
  width: 100%;
}

.average-button-wrap {
  display: table-cell;
}

.average-button {
  margin-left: .5rem;
  margin-right: .5rem;
}

.average-button-wrap:first-child .average-button {
  margin-left: 0;
}

.average-button-wrap:last-child .average-button {
  margin-right: 0;
}

.average-button {
  display: block;
  border: 1px solid currentColor;
  background: transparent;
  border-radius: 1rem;
  white-space: nowrap;
  color: #ef7077;
}
```

```html
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
</div>
<div class="average-button-group">
  <div class="average-button-wrap">
    <a class="average-button" role="button">按</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮按</a>
  </div>
  <div class="average-button-wrap">
    <a class="average-button" role="button">按钮按钮</a>
  </div>
</div>
```

**Comment by brenner8023** [comment]
[在线demo](https://codepen.io/brenner8023/pen/KjXgrR)

```html
<style>
  .container {
  width: 50%;
  margin: 1rem auto;
  background: #ddd;
  display: flex;
  padding: 1rem 0.5rem;
}
.item {
  margin: 0 0.5rem;
  width: 100%;
  height: 2rem;
  outline: none;
  border: 1px solid red;
  border-radius: 1rem;
  color: red;
}
</style>
<body>
   <div class="container">
    <button class="item">按钮</button>
</div>
 <div class="container">
  <button class="item">按钮</button>
  <button class="item">按钮</button>
</div>
<div class="container">
  <button class="item">按钮</button>
  <button class="item">按钮</button>
  <button class="item">按钮</button>
</div>
</body>
```

**Comment by sghweb** [comment]
[demo](https://codepen.io/sghweb/pen/dBVOXp)
```html
<div class="btn">
  <button class="btn__item">按钮</button>
  <button class="btn__item">按钮</button>
  <button class="btn__item">按钮</button>
  <button class="btn__item">按钮</button>
  <button class="btn__item">按钮</button>
</div>
```
```css
body{
  margin: 0;
}
.btn{
  display:flex;
  padding:10px;
  background: #f7f7f7;
}
.btn__item{
  display:flex;
  align-items: center;
  justify-content: center;
  flex:1;
  padding: 6px 0;
  text-align: center;
  color: #ef7077;
  margin-right:1rem;
  background: transparent;
  border: 1px solid;
  border-radius: 10em;
}
.btn__item:last-child{
  margin-right: 0;
}
```

**Comment by XboxYan** [comment]
[demo](https://codepen.io/xboxyan/pen/bPoBKQ)

```css
.btn {
    padding: .5em 1em;
    text-align: center;
    background: none;
    border: 1px solid;
    font-size:1rem;
    border-radius: 5em;
    color: #ef7077;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
.btn-group{
    display: flex;
    padding: .5rem;
}
.btn-group .btn{
    flex: 1;
    margin: 0 .5rem;
}
```

```html
<div class="btn-group">
    <button class="btn">很多文字的按钮按钮按钮按钮按钮按钮按钮按钮按钮按钮按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
</div>
```

**Comment by livetune** [comment]
```html
<div class="button-list">
        <button>按钮</button>
    </div>
    <div class="button-list">
        <button>按钮</button>
        <button>按钮</button>
    </div>
    <div class="button-list">
        <button>按钮</button>
        <button>按钮</button>
        <button>按钮</button>
    </div>
```

```css
.button-list {
    display: flex;
}

.button-list button:first-child {
    margin-left: 1rem;
}

.button-list button {
    flex: 1;
    font-size: 14px;
    color: #ef7077;
    background: inherit;
    border-radius: 9999px;
    border: 1px solid #ef7077;
    margin-right: 1rem;
}
```

**Comment by sanshiliuxiao** [comment]
## [Demo](https://jsbin.com/gezisew/7/edit?html,css,output)

```html
  <div class="container">
    <button class="btn">按钮</button>
  </div>
    <div class="container">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
    <div class="container">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
    <div class="container">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
```
```css
body {
  margin: 0;
}
.container {
  display: flex;
  padding-left: 0.5rem;
  padding-right: 0.5rem;
  
  
  margin-top: 10px;
}
.btn {
  flex: 1;
  border: 1px solid red;
  outline: none;
  background: none;
  height: 26px;
  line-height: 26px;
  border-radius: 13px;
  margin: 0 0.5rem ;
  overflow: hidden;
}
```

**Comment by qianfengg** [comment]
[demo](https://jsbin.com/gigayer/edit?html,css,output)
```html
    <div class="btn-group">
        <button>点击</button>
    </div>
    <div class="btn-group">
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
    </div>
    <div class="btn-group">
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
    </div>
    <div class="btn-group">
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
        <button>点击</button>
    </div>
```
```css
        body{
            margin: 0;
        }
        .btn-group{
            display: flex;
            justify-content: space-between;
            margin: 10rem 0;
        }
        button{
            text-align: center;
            width: 100%;
            cursor: pointer;
            border-radius: 10rem;
            background-color: transparent;
            border: 1px solid #ccc;
            outline: none;
            margin: 0 0.5rem;
        }
```

**Comment by NeilC1991** [comment]
demo
https://codepen.io/crazyboy/pen/MMEraE
```html
<div class="container1">
	<button>按钮</button>
	<button>按钮</button>
	<button>按钮</button>
	<button>按钮</button>
	<button>按钮</button>
	<button>按钮</button>
</div>
<div class="container2">
	<div><button>按钮</button></div>
	<div><button>按钮</button></div>
	<div><button>按钮</button></div>
	<div><button>按钮</button></div>
	<div><button>按钮</button></div>
	<div><button>按钮</button></div>
</div>
```
```css
body {
	margin: 0;
}
button {
	text-align: center;
	border: 1px solid red;
	border-radius: 1rem;
	background: transparent;
}
/* 方法1 flex */
.container1 {
	display: flex;
	margin-left: 1rem;
}
.container1>button {
	flex-grow: 1;
	margin-right: 1rem;
}
/* 方法2 table */
.container2 {
	display: table;
	white-space: nowrap;
	width: calc(100% - 1rem);
	margin-left: 1rem;
}
.container2>div {
	display: table-cell;
	padding-right: 1rem;
}
.container2>div>button {
	width: 100%;
}
```

**Comment by tzmy** [comment]
[在线DEMO](https://codepen.io/tzmy/pen/wLrNMP)
```css
body,html{
    margin: 0;
    padding: 0;
}

button{
    background: none;
    border: 1px solid #ef7077;
    color:#ef7077;
    height: 30px;
    flex: 1;
    margin: 0.5rem;
    border-radius: 20px;
}
.button_box{
    display: flex;
    margin: 0 0.5rem;
}
```
```html
<div class="button_box">
  <button>按钮</button>
</div>
<div class="button_box">
  <button>按钮</button>
  <button>按钮</button>
</div>
<div class="button_box">
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
  <button>按钮</button>
</div>
```

**Comment by smileyby** [comment]
[在线预览DEMO](https://codepen.io/smileyby/pen/MMELdg)
```html
<div class="btn-group">
  <button class="btn">按钮</button>
</div>
<div class="btn-group">
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
</div>
<div class="btn-group">
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
</div>
<div class="btn-group">
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
  <button class="btn">按钮</button>
</div>
```
```css
.btn-group {
  display: -webkit-flex;
  display: flex;
  padding: 1rem;
  margin-bottom: 1rem;
  background: #f6f7f9;
}

.btn {
  flex: 1;
  height: 30px;
  margin-right: 1rem;
  border: 2px solid #ef7077;
  border-radius: 15px;
  color: #ef7077;
  background: transparent;
  box-sizing: border-box;
  outline: none;
}

.btn:focus {
  background: #fff;
}

.btn:last-child {
  margin-right: 0;
}
```

**Comment by wewrt** [comment]
[demo](https://codepen.io/baojin/pen/xoXoOd)
```html
<div class="btn_container">
  <button class="btn_item">按钮</button>
  <button class="btn_item">按钮</button>  
  <button class="btn_item">按钮</button>
</div>
```
```SCSS
.btn_container {
  display: flex;
  flex-wrap: nowrap;
  .btn_item {
    + .btn_item {
      margin-left: 1rem;
    }
    &:focus {
      outline: none;
    }
    flex: 1;
    color: #ef7077;
    border: 1px solid;
    background: none;
    border-radius: 10rem;
  }
}

```

**Comment by AsyncGuo** [comment]
[demo](https://codepen.io/asyncguo/pen/pXRYJL)
```html
<div class="button-group">
  <button class="button-item">按钮</button>
</div>
<div class="button-group">
  <button class="button-item">按钮</button>
  <button class="button-item">按钮</button>
</div>
<div class="button-group">
  <button class="button-item">按钮</button>
  <button class="button-item">按钮</button>
  <button class="button-item">按钮</button>
</div>
```
```css
.button-group{
  display: flex;
  margin: 0 1rem 1rem 1rem;
  .button-item{
    flex: 1;
    background-color: #fff;
    border: 1px solid #f56c6c;
    border-radius: 2em;
    color: #f56c6c;
    outline: none;
    padding: .5rem;
    &:not(:last-child) {
      margin-right: 1rem;
    }
  }
}
```

**Comment by frankyeyq** [comment]
[demo](https://codepen.io/anon/pen/rEYBPa)
```html
<div class="buttons-container">
        <div class="button">按钮</div>
    </div>
    <div class="buttons-container">
        <div class="button">按钮</div>
        <div class="button">按钮</div>
    </div>
    <div class="buttons-container">
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
    </div>
    <div class="buttons-container">
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
        <div class="button">按钮</div>
    </div>
```
```css
html {
        font-size: 16px;
        margin: 0;
    }
    body {
        margin: 0;
    }
    .buttons-container {
        display: flex;
        padding: 1rem;
    }
    .buttons-container .button:first-child {
        margin-left: 0
    }
    .buttons-container .button:last-child {
        margin-right: 0;
    }
    .button {
        flex: auto;
        height: 20px;
        line-height: 20px;
        box-sizing: border-box;
        border: 1px solid #f1949a;
        color: #f1949a;
        font-size: 12px;
        border-radius: 20px;
        text-align: center;
        margin: 0 0.5rem;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
```

**Comment by Jiarui-Zeng** [comment]
[demo](https://codepen.io/jiarui-zeng/pen/xoPKBO)

```html
<div class="btn-group">
  <button class="cus-btn">按钮</button>
</div>

<div class="btn-group">
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
</div>

<div class="btn-group">
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
</div>
```

```css
.btn-group {
  display: flex;
  flex-wrap: nowrap;
  padding: 0 0 1rem 1rem ;
}
.cus-btn {
  flex: 1;
  margin-right: 1rem;
  color: red;
  border: 1px solid red;
  border-radius: 1em;
  background: transparent;
  white-space: nowrap;
}
```

**Comment by Forx-Js** [comment]
\> [点击这里](https://codepen.io/forx-js/pen/agVdvG?editors=1100) \<

```css
$gutter: 1rem;                     //自定义 间隔
$color: #dd0000;                 //自定义按钮颜色
.main {
  background-color: #f5f5f5;
  padding: 16px;
}
.row {
  border: 1px solid black;   // 不要觉得丑 主要用来体现与按钮组的宽度关系
  display: flex;
  flex-basis: row nowrap;
  justify-content: space-around;
}
.col {
  flex: 1 1; //等比缩放
  & + & {
    margin-left: $gutter;          // 不是第一个元素时拉开边距
  }
}
.btn {                                  // 按钮样式,没什么好看的
  color: $color;
  width: 100%;                    //  保持行内块元素,不想变成块
  font-size: 16px;
  background: none;
  padding: 8px 3px;
  border-radius: 20px;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
  outline: none;
  border: 1px solid currentcolor;
  transition: all 0.2s;
  &:active {                                              // 偷懒,就写了点击时样式
    $color2: adjust-hue($color, -10);
    $color3: fade-out($color2, 0.3);
    color: $color2;
    box-shadow: 0 0 8px -4px $color3;
    background-color: rgba($color3, 0.1);
  }
}

```

**Comment by xxf1996** [comment]
[demo](https://codepen.io/xxf1996/pen/gNXwLO)
```html
<section class="container">
  <div class="container-row">
    <button class="btn">按钮</button>
  </div>
  <div class="container-row">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
  <div class="container-row">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
  <div class="container-row">
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
    <button class="btn">按钮</button>
  </div>
</section>
```

```css
.container {
  overflow: hidden;
  background-color: #f6f6f6;
}
.container-row {
  display: flex;
  flex-flow: row nowrap;
  justify-content: space-between;
  margin: 20px 1rem;
}
.btn {
  flex: 1;
  margin-right: 1rem;
  height: 28px;
  line-height: 28px;
  outline: 0;
  border-radius: 14px;
  border: 1px solid #f36;
  color: #f36;
  background-color: transparent;
  overflow: hidden;
}
.btn:last-child {
  margin-right: 0;
}
```

后面想到也许grid布局更合适。

**Comment by jsweber** [comment]
[demo](https://codepen.io/jsweber/pen/PrORPa)

```css
        body{
            margin: 0
        }
        .btn-wrapper{
            display: flex;
            flex-wrap: nowrap;
            background: #eee;
            padding: 10px 0;
        }
        .btn {
            outline: none;
            border: 1px solid #ef7b82;
            color: #ef7b82;
            padding: 6px 0;
            border-radius: 1em;
            background-color: #fff;
            flex-basis: 10em;
            flex: 1;
            margin: 0 0.5rem;
        }

        .btn:first-of-type{
            margin-left: 1rem;
        }

        .btn:last-of-type {
            margin-right: 1rem;
        }

```

**Comment by xueyixiao** [comment]
### <a href="https://codepen.io/jialongfei/pen/eweoNW">点击查看demo</a>
``` css
        .btn {
		color: red;
		background: none;
		border: red 1px solid;
		border-radius: 50px;
		width: 100%;
		margin: 0 0.5rem;
		padding: 0.5rem;
		overflow: hidden;
	}
	.btn-group {
		padding: 0.5rem;
		display: flex;
	}
 ``` 
``` html
                <div class="btn-group">
			<button class="btn">按钮</button>
		</div>
		<div class="btn-group">
			<button `class="btn">按钮</button>`
			<button class="btn">按钮</button>
		</div>
		<div class="btn-group">
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
		</div>
		<div class="btn-group">
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
			<button class="btn">按钮</button>
		</div>

**Comment by Despair-lj** [comment]
[demo](https://codepen.io/despair-lj/pen/ydpBzx)

```html
<div class="ui-container">
  <a href="javascript:" class="ui-button" role="button">按钮</a>
</div>
<div class="ui-container">
  <a href="javascript:" class="ui-button" role="button">按钮</a>
  <a href="javascript:" class="ui-button" role="button">按钮</a>
</div>
<div class="ui-container">
  <a href="javascript:" class="ui-button" role="button">按钮</a>
  <a href="javascript:" class="ui-button" role="button">按钮</a>
  <a href="javascript:" class="ui-button" role="button">按钮</a>
</div>
```

```css
.ui-button {
  display: inline-block;
  margin: 0 0.5rem;
  padding: 9px 15px;
  line-height: 20px;
  font-size: 14px;
  text-align: center;
  color: #f4615c;
  border: 1px solid;
  border-radius: 20px;
  min-width: 50px;
  text-decoration: none;
  cursor: pointer;
}
.ui-button:hover {
  background-color: #aa4642;
  color: #fff;
}
.ui-container {
  display: flex;
  margin: 0.5rem;
}
.ui-container .ui-button {
  flex: 1;
}
```

**Comment by yuhaocan** [comment]
[demo](https://codepen.io/yuhaocan/pen/MMORpm)

```html
<div class="btn_wrapper">
  <button>按钮</button>
</div>
```

```css
.btn_wrapper {
  margin: 10px;
  display: flex;
  border: 1px solid black;
  padding-left: 1rem;
}

button {
  border: 2px solid pink;
  padding: 5px 10px;
  margin-right: 1rem;
  border-radius: 20px;
  background: none;

  white-space: nowrap;
  flex: 1;
  
  color: pink;
  font-size: medium;
  text-overflow: ellipsis;
  overflow: hidden;
}

```

**Comment by tao1874** [comment]
```css
.box {
      padding: 0 1em;
      display: grid;
      grid-auto-flow: column;
      grid-gap: 1em;
    }
    .btn {
      border: 1px solid #ef777e;
      border-radius: 1em;
      text-align: center;
      line-height: 1.5em;
    }
```
[DEMO](https://codepen.io/tao1874/pen/OezjvP)
