### ISSUE TITLE
DOM基础测试44期

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#65]
我们接着上一期CSS布局效果，产品经理发话了，希望可以轮播，就是大的变小，小的变大，从右往左轮播。你该如何实现？

<img src="https://imgservices-1252317822.image.myqcloud.com/image/20200220/hyesu1bc4o.png">

<a href="https://imgservices-1252317822.image.myqcloud.com/image/20200220/hyesu1bc4o.png">原图不显示可以点击这里</a>

大家提交回答的时候，注意缩进距离，起始位置从左边缘开始；另外，github自带代码高亮，所以请使用下面示意的格式。

最好提供在线的demo。

<pre>```js
// 你的JS代码写在这里
 ```</pre>

**其他**
本期小测没有直播，也没有打分，但是会反馈要点。

**Comment by liyongleihf2006** [comment]
[jsbin](https://jsbin.com/waheruk/edit?html,css,js,output)
```css
.rotate-ul {
    --seed: 0;
    transform-style: preserve-3d;
    perspective: 800px;
    display: inline-block;
    white-space: nowrap;
    padding-left: 0;
}

.rotate-li {
    display: inline-block;
    list-style: none;
}

.rotate-li:nth-child(1) {
    transform: translateZ(calc((var(--seed) + 200)*(var(--seed) + 200)*-.01px)) translateX(calc(var(--seed)*-1% ));
}

.rotate-li:nth-child(2) {
    transform: translateZ(calc((var(--seed) + 100)*(var(--seed) + 100)*-.01px)) translateX(calc(var(--seed)*-1% ));
}

.rotate-li:nth-child(3) {
    transform: translateZ(calc((var(--seed) + 0)*(var(--seed) + 0)*-.01px)) translateX(calc(var(--seed)*-1% ));
}

.rotate-li:nth-child(4) {
    transform: translateZ(calc((var(--seed) - 100)*(var(--seed) - 100)*-.01px)) translateX(calc(var(--seed)*-1% ));
}

.rotate-li:nth-child(5) {
    transform: translateZ(calc((var(--seed) - 200)*(var(--seed) - 200)*-.01px)) translateX(calc(var(--seed)*-1% ));
}

.rotate-ul-ani{
    animation:1s 3s ani linear;
}

@keyframes ani {
    0%{--seed:0}1%{--seed:1}2%{--seed:2}3%{--seed:3}4%{--seed:4}5%{--seed:5}6%{--seed:6}7%{--seed:7}8%{--seed:8}9%{--seed:9}10%{--seed:10}11%{--seed:11}12%{--seed:12}13%{--seed:13}14%{--seed:14}15%{--seed:15}16%{--seed:16}17%{--seed:17}18%{--seed:18}19%{--seed:19}20%{--seed:20}21%{--seed:21}22%{--seed:22}23%{--seed:23}24%{--seed:24}25%{--seed:25}26%{--seed:26}27%{--seed:27}28%{--seed:28}29%{--seed:29}30%{--seed:30}31%{--seed:31}32%{--seed:32}33%{--seed:33}34%{--seed:34}35%{--seed:35}36%{--seed:36}37%{--seed:37}38%{--seed:38}39%{--seed:39}40%{--seed:40}41%{--seed:41}42%{--seed:42}43%{--seed:43}44%{--seed:44}45%{--seed:45}46%{--seed:46}47%{--seed:47}48%{--seed:48}49%{--seed:49}50%{--seed:50}51%{--seed:51}52%{--seed:52}53%{--seed:53}54%{--seed:54}55%{--seed:55}56%{--seed:56}57%{--seed:57}58%{--seed:58}59%{--seed:59}60%{--seed:60}61%{--seed:61}62%{--seed:62}63%{--seed:63}64%{--seed:64}65%{--seed:65}66%{--seed:66}67%{--seed:67}68%{--seed:68}69%{--seed:69}70%{--seed:70}71%{--seed:71}72%{--seed:72}73%{--seed:73}74%{--seed:74}75%{--seed:75}76%{--seed:76}77%{--seed:77}78%{--seed:78}79%{--seed:79}80%{--seed:80}81%{--seed:81}82%{--seed:82}83%{--seed:83}84%{--seed:84}85%{--seed:85}86%{--seed:86}87%{--seed:87}88%{--seed:88}89%{--seed:89}90%{--seed:90}91%{--seed:91}92%{--seed:92}93%{--seed:93}94%{--seed:94}95%{--seed:95}96%{--seed:96}97%{--seed:97}98%{--seed:98}99%{--seed:99}100%{--seed:100}
}
```
```html
<ul id="rotateUl" class="rotate-ul rotate-ul-ani">
    <li class="rotate-li">
        <img src="https://i.picsum.photos/id/1025/200/300.jpg" />
    </li>
    <li class="rotate-li">
        <img src="https://i.picsum.photos/id/219/200/300.jpg" />
    </li>
    <li class="rotate-li">
        <img src="https://i.picsum.photos/id/237/200/300.jpg" />
    </li>
    <li class="rotate-li">
        <img src="https://i.picsum.photos/id/275/200/300.jpg" />
    </li>
    <li class="rotate-li">
        <img src="https://i.picsum.photos/id/433/200/300.jpg" />
    </li>
</ul>
```
```js
document.querySelector("#rotateUl").addEventListener('animationend',function(){
    const firstChild = this.firstElementChild
    this.append(firstChild)
    this.classList.remove('rotate-ul-ani')
    this.offsetWidth
    this.classList.add('rotate-ul-ani')
})
```

**Comment by livetune** [comment]
```css
li {
    width: 100px;
    height: 150px;
    list-style: none;
    margin: 0;
    transition: .8s;
}

ul {
    display: flex;
    align-items: center;
}


li:nth-child(1) {
    transform: scale(.8) translateX(100%);
}

li:nth-child(2) {
    transform: scale(.9) translateX(50%);
}

li:nth-child(3) {
    transform: scale(1) translateX(0);
    z-index: 1;
}

li:nth-child(4) {
    transform: scale(.9) translateX(-50%);
}

li:nth-child(5) {
    transform: scale(.8) translateX(-100%);
    z-index: -1;
}


img {
    width: 100%;
}

.change li:nth-child(1) {
    width: 0;
    height: 0;
    opacity: 0;
    transition: .6s;
}


.change li:nth-child(2) {
    transform: scale(.8) translateX(100%);
}

.change li:nth-child(3) {
    transform: scale(.9) translateX(50%);
}

.change li:nth-child(4) {
    transform: scale(1) translateX(0);
    z-index: 1;
}

.change li:nth-child(5) {
    transform: scale(.9) translateX(-50%);
}
```

```html
<ul>
    <li> <img src="https://i.picsum.photos/id/1025/200/300.jpg"> </li>
    <li> <img src="https://i.picsum.photos/id/219/200/300.jpg" /> </li>
    <li> <img src="https://i.picsum.photos/id/237/200/300.jpg" /> </li>
    <li> <img src="https://i.picsum.photos/id/275/200/300.jpg" /> </li>
    <li> <img src="https://i.picsum.photos/id/433/200/300.jpg" /> </li>
</ul>
```
```js
    setInterval(() => {
        const ul = document.querySelector('ul')
        ul.classList.add('change')
        const first = ul.querySelector('li')
        const activeNext = document.querySelector('li.active+li').classList.add('active')
        setTimeout(() => {
            ul.append(first)
            ul.classList.remove('change')
        }, 600)
    }, 1200)
```

**Comment by qianfengg** [comment]
[demo](https://codepen.io/qianfengg/pen/KKpZKEO)
```html
    <ul class="active">
      <li> <img src="https://i.picsum.photos/id/1025/200/300.jpg"> </li>
      <li> <img src="https://i.picsum.photos/id/219/200/300.jpg" /> </li>
      <li> <img src="https://i.picsum.photos/id/237/200/300.jpg" /> </li>
      <li> <img src="https://i.picsum.photos/id/275/200/300.jpg" /> </li>
      <li> <img src="https://i.picsum.photos/id/433/200/300.jpg" /> </li>
    </ul>
```
```css
* {
  padding: 0;
  margin: 0;
}
ul,
li {
  list-style: none;
}
body {
  display: flex;
  min-height: 100vh;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  perspective: 800px;
}
ul {
  --seed: 0;
  display: flex;
  transform-style: preserve-3d;
}

ul > li:nth-child(1) {
  transform: translateZ(
      calc((var(--seed) + 200) * (var(--seed) + 200) * -0.01px)
    )
    translateX(calc(var(--seed) * -1%));
}
ul > li:nth-child(2) {
  transform: translateZ(
      calc((var(--seed) + 100) * (var(--seed) + 100) * -0.01px)
    )
    translateX(calc(var(--seed) * -1%));
}
ul > li:nth-child(3) {
  transform: translateZ(calc((var(--seed) + 0) * (var(--seed) + 0) * -0.01px))
    translateX(calc(var(--seed) * -1%));
}
ul > li:nth-child(4) {
  transform: translateZ(
      calc((var(--seed) - 100) * (var(--seed) - 100) * -0.01px)
    )
    translateX(calc(var(--seed) * -1%));
}
ul > li:nth-child(5) {
  transform: translateZ(
      calc((var(--seed) - 200) * (var(--seed) - 200) * -0.01px)
    )
    translateX(calc(var(--seed) * -1%));
}

ul.active {
  animation: 0.5s anim linear;
}

@keyframes anim {
  0% {
    --seed: 0;
  }
  1% {
    --seed: 1;
  }
  2% {
    --seed: 2;
  }
  3% {
    --seed: 3;
  }
  4% {
    --seed: 4;
  }
  5% {
    --seed: 5;
  }
  6% {
    --seed: 6;
  }
  7% {
    --seed: 7;
  }
  8% {
    --seed: 8;
  }
  9% {
    --seed: 9;
  }
  10% {
    --seed: 10;
  }
  11% {
    --seed: 11;
  }
  12% {
    --seed: 12;
  }
  13% {
    --seed: 13;
  }
  14% {
    --seed: 14;
  }
  15% {
    --seed: 15;
  }
  16% {
    --seed: 16;
  }
  17% {
    --seed: 17;
  }
  18% {
    --seed: 18;
  }
  19% {
    --seed: 19;
  }
  20% {
    --seed: 20;
  }
  21% {
    --seed: 21;
  }
  22% {
    --seed: 22;
  }
  23% {
    --seed: 23;
  }
  24% {
    --seed: 24;
  }
  25% {
    --seed: 25;
  }
  26% {
    --seed: 26;
  }
  27% {
    --seed: 27;
  }
  28% {
    --seed: 28;
  }
  29% {
    --seed: 29;
  }
  30% {
    --seed: 30;
  }
  31% {
    --seed: 31;
  }
  32% {
    --seed: 32;
  }
  33% {
    --seed: 33;
  }
  34% {
    --seed: 34;
  }
  35% {
    --seed: 35;
  }
  36% {
    --seed: 36;
  }
  37% {
    --seed: 37;
  }
  38% {
    --seed: 38;
  }
  39% {
    --seed: 39;
  }
  40% {
    --seed: 40;
  }
  41% {
    --seed: 41;
  }
  42% {
    --seed: 42;
  }
  43% {
    --seed: 43;
  }
  44% {
    --seed: 44;
  }
  45% {
    --seed: 45;
  }
  46% {
    --seed: 46;
  }
  47% {
    --seed: 47;
  }
  48% {
    --seed: 48;
  }
  49% {
    --seed: 49;
  }
  50% {
    --seed: 50;
  }
  51% {
    --seed: 51;
  }
  52% {
    --seed: 52;
  }
  53% {
    --seed: 53;
  }
  54% {
    --seed: 54;
  }
  55% {
    --seed: 55;
  }
  56% {
    --seed: 56;
  }
  57% {
    --seed: 57;
  }
  58% {
    --seed: 58;
  }
  59% {
    --seed: 59;
  }
  60% {
    --seed: 60;
  }
  61% {
    --seed: 61;
  }
  62% {
    --seed: 62;
  }
  63% {
    --seed: 63;
  }
  64% {
    --seed: 64;
  }
  65% {
    --seed: 65;
  }
  66% {
    --seed: 66;
  }
  67% {
    --seed: 67;
  }
  68% {
    --seed: 68;
  }
  69% {
    --seed: 69;
  }
  70% {
    --seed: 70;
  }
  71% {
    --seed: 71;
  }
  72% {
    --seed: 72;
  }
  73% {
    --seed: 73;
  }
  74% {
    --seed: 74;
  }
  75% {
    --seed: 75;
  }
  76% {
    --seed: 76;
  }
  77% {
    --seed: 77;
  }
  78% {
    --seed: 78;
  }
  79% {
    --seed: 79;
  }
  80% {
    --seed: 80;
  }
  81% {
    --seed: 81;
  }
  82% {
    --seed: 82;
  }
  83% {
    --seed: 83;
  }
  84% {
    --seed: 84;
  }
  85% {
    --seed: 85;
  }
  86% {
    --seed: 86;
  }
  87% {
    --seed: 87;
  }
  88% {
    --seed: 88;
  }
  89% {
    --seed: 89;
  }
  90% {
    --seed: 90;
  }
  91% {
    --seed: 91;
  }
  92% {
    --seed: 92;
  }
  93% {
    --seed: 93;
  }
  94% {
    --seed: 94;
  }
  95% {
    --seed: 95;
  }
  96% {
    --seed: 96;
  }
  97% {
    --seed: 97;
  }
  98% {
    --seed: 98;
  }
  99% {
    --seed: 99;
  }
  100% {
    --seed: 100;
  }
}
```
```js
{
  let timer = 0;
  document.querySelector("ul").addEventListener("animationend", function() {
    clearTimeout(timer);
    const firstLi = this.firstElementChild;
    this.append(firstLi);
    this.classList.remove("active");
    timer = setTimeout(() => {
      this.classList.add("active");
    }, 1000);
  });
}

```

**Comment by xxf1996** [comment]
我的思路是过渡效果+节点移动；突然觉得我这做法有“替身使者”内味了……

[demo](https://codepen.io/xxf1996/pen/zYGRNKX)

```css
html,
body {
  margin: 0;
  padding: 0;
}
#demo {
  position: relative;
  perspective: 200px;
  transform-style: preserve-3d;
  overflow: hidden;
}
#demo::after {
  content: '';
  display: block;
  padding-top: 42.7%; /* 宽高比参照375/160 */
}
.pic {
  position: absolute;
  height: 100%;
  transition: all .5s ease-in-out;
}
.pic:nth-of-type(1) {
  left: 10%;
  transform: translateX(-50%) translateZ(-30px);
}
.pic:nth-of-type(2) {
  left: 30%;
  transform: translateX(-50%) translateZ(-15px);
}
.pic:nth-of-type(3) {
  left: 50%;
  transform: translateX(-50%);
}
.pic:nth-of-type(4) {
  left: 70%;
  transform: translateX(-50%) translateZ(-15px);
  z-index: -1;
}
.pic:nth-of-type(5) {
  left: 90%;
  transform: translateX(-50%) translateZ(-30px);
  z-index: -2;
}
.pic:nth-of-type(6) {
  left: 10%;
  transform: translateX(-50%) translateZ(-30px);
  opacity: 0;
}
```

```html
<div id="demo">
  <img class="pic" src="https://placem.at/things?w=100&h=160&txt=1">
  <img class="pic" src="https://placem.at/people?w=100&h=160&txt=2">
  <img class="pic" src="https://placem.at/places?w=100&h=160&txt=3">
  <img class="pic" src="https://placem.at/people?w=100&h=160&txt=4">
  <img class="pic" src="https://placem.at/things?w=100&h=160&txt=5">
</div>
```

```js
let demo = document.getElementById('demo')

function toggle (init = false) {
  let first = demo.querySelector('.pic')
  if (init) {
    /* 
        ** 多出一个子元素来替第一个子元素提前占位，避免第一个子元素移到最后一个时不能触发过渡（因为第一个子元素实际上是先移出，再插入的）
        ** 实际上由于最后一个子元素永远是第一个子元素的复本，相当于移动时，从最后一个往前一位，这样就能触发过渡了
        */
    let firstCopy = first.cloneNode()
    demo.appendChild(firstCopy) 
  } else {
    let second = demo.querySelector('.pic:nth-of-type(2)')
    demo.appendChild(first) // 将最第一个子元素插入到最后
    first.outerHTML = second.outerHTML // 将最后一个子元素实时更新为当前第一个子元素的复本
  }
}

toggle(true)
setInterval(toggle, 3000)
```

**Comment by zer0fire** [comment]
[demo](https://jsbin.com/qijizazope/1/edit?html,css,js,output)

```css
    ul {
      list-style: none;
      padding: 0;
      margin: 0;
      transform-style: preserve-3d;
      /* display: inline; */
      /* justify-content: center; */
      align-items: center;
      margin: 45px;
    }
    li {
      display: inline-block;
      list-style: none;
    }
    .img-container {
      transition: all .5s linear;
      position: absolute;
    }
    .img-container:nth-child(1) {
      transform: scale(1);
      left: 100px;
      z-index: 1;
    }
    .img-container:nth-child(2) {
      transform: scale(1.1);
      left: 200px;
      z-index: 5;
    }
    .img-container:nth-child(3) {
      transform: scale(1.2);
      left: 300px;
      z-index: 10;
    }
    .img-container:nth-child(4) {
      transform: scale(1.1);
      left: 400px;
      z-index: 5;
    }
    .img-container:nth-child(5) {
      transform: scale(1);
      left: 500px;
      z-index: 1;
    }
    .img-container:nth-child(6) {
      left: 600px;
      transform: scale(1);
      opacity: 0;
    }
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DOM44</title>
</head>
<body>
  <ul class="img-list">
    <li class="img-container" ><img src="https://via.placeholder.com/120x150/00FFFF/808080?1" alt=""></li>
    <li class="img-container" ><img src="https://via.placeholder.com/120x150/FF00FF/808080?2" alt=""></li>
    <li class="img-container" ><img src="https://via.placeholder.com/120x150/0FF0FF/808080?3" alt=""></li>
    <li class="img-container" ><img src="https://via.placeholder.com/120x150/0000FF/808080?4" alt=""></li>
    <li class="img-container" ><img src="https://via.placeholder.com/120x150/0FF0FF/808080?5" alt=""></li>
  </ul>
</body>
</html>
```
```js
  let cacheNode = document.querySelector('.img-container:nth-child(1)')
  let container = document.querySelector('.img-list')
  let sixthNode = document.createElement('li')
  container.appendChild(sixthNode)
  // debugger;
  sixthNode.outerHTML = cacheNode.outerHTML

  setInterval(() => {
    let first = document.querySelector('.img-container:nth-child(1)')
    let sixthNode = document.querySelector('.img-container:nth-child(6)')
    container.appendChild(first)
    sixthNode.children[0].src = first.children[0].src
  }, 3000)
```
