### ISSUE TITLE
CSS基础测试20期

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#69]
实现一个有些挑战的布局：

<img src="https://imgservices-1252317822.file.myqcloud.com/image/20200401/tmic9crjvq.png">

图片无法访问<a href="https://imgservices-1252317822.file.myqcloud.com/image/20200401/tmic9crjvq.png">点击这里</a>

本题不需要考虑视觉还原，主要是布局效果实现。

请附上对应的CSS代码，注意缩进和代码高亮，可以使用下面语法进行高亮：

<pre>```html
你的代码在这里
```</pre>
<pre>```css
你的代码在这里
```</pre>

本期小测需要提供在线demo，不要参考别人的回答，诚实守信。

本期小测无直播答疑，但是会总结要点。

感谢您的参与！

**Comment by LuckyRabbitFeet** [comment]
html
```html
<div class="box limit">
  <span>111</span>
  <span>222</span>
  <span>333</span>
  <span>444</span>
  <span>555</span>
</div>
```

css
```css
.limit {
  width: 150px;
}

.box {
  display: flex;
  flex-wrap: wrap;
  height: 30px;
  overflow: hidden;
}

.box span {
  flex-shrink: 0;
  width: 98px;
  height: 28px;
  border: 1px solid black;
}
```

**Comment by zer0fire** [comment]
[Demo](url)
用 flex 实现弹性布局

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <main>
    <div>a</div>
    <div>b</div>
    <div>c</div>
    <div>d</div>
    <div>e</div>
  </main>
</body>
</html>
```

```css
main {
  display: flex;
  width: 100%;
  flex-wrap: wrap;
  overflow: hidden;
  height: 27px;
}

div {
  height: 25px; 
  flex-basis: 150px;
  text-align: center;
  border: 1px solid;
  flex-grow: 1;
}
main::before {
  content: '<';
  position: absolute;
  left: -2px;
}
main::after {
  content: '>';
  position: absolute;
  right: -2px;
}
```

**Comment by livetune** [comment]
[DEMO](https://codepen.io/livetune/pen/XWbGLGQ?editors=1100)
虽然是实现的，但是html嵌套的有点深。。

```html
<section class="date-picker-wrapper">
    <icon class="arrow left-icon"></icon>
    <div class="date-picker-col-wrapper">
        <i class="date-picker-col-padding"></i>
        <ul class="date-picker">
            <li>2020年4月-6月</li>
            <li>2020年1月-3月</li>
            <li>2020 年度 OKR</li>
        </ul>
    </div>
    <icon class="arrow right-icon"></icon>
</section>
```
```css
.arrow {
    display: inline-block;
    width: 30px;
    height: 30px;
    background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj4gPHBhdGggZD0iTTM0LjUyIDIzOS4wM0wyMjguODcgNDQuNjljOS4zNy05LjM3IDI0LjU3LTkuMzcgMzMuOTQgMGwyMi42NyAyMi42N2M5LjM2IDkuMzYgOS4zNyAyNC41Mi4wNCAzMy45TDEzMS40OSAyNTZsMTU0LjAyIDE1NC43NWM5LjM0IDkuMzggOS4zMiAyNC41NC0uMDQgMzMuOWwtMjIuNjcgMjIuNjdjLTkuMzcgOS4zNy0yNC41NyA5LjM3LTMzLjk0IDBMMzQuNTIgMjcyLjk3Yy05LjM3LTkuMzctOS4zNy0yNC41NyAwLTMzLjk0eiI+PC9wYXRoPiA8L3N2Zz4=  ) center no-repeat;
    background-size: 10px;
}

.right-icon {
    border-right: 1px solid #ddd;
    transform: rotateZ(180deg);
}

body {
    background: #f1f1f1;

}

.arrow {
    flex: 0 0 30px;
}

.date-picker-wrapper {
    display: flex;
    width: 100%;
    background: #fff;
    justify-content: space-between;
    align-items: center;
    height: 30px;
    margin-top: 40px;
    overflow: hidden;

}

.date-picker {
    display: flex;
    flex-wrap: wrap;
    flex: 1;
    list-style: none;
    white-space: nowrap;
    padding: 0;
    margin: 0;
}

li {
    line-height: 30px;
    flex: 1;
    text-align: center;
    padding: 0 40px;
    height: 30px;
    border-left: 1px solid #ddd;

}

li:nth-child(2) {
    color: skyblue;
}

.date-picker-col-wrapper {
    display: flex;
    flex: 1;
    flex-direction: column;
    height: 90px;
}

.date-picker-col-padding {
    flex: 1;
    max-height: calc(100% / 3);
}
```

**Comment by xiejiaxing1994** [comment]
> 实现一个有些挑战的布局：
> 
> ![](https://camo.githubusercontent.com/b93a3faa6d59dae0460befb63107f40ac9d8c7ee/68747470733a2f2f696d6773657276696365732d313235323331373832322e66696c652e6d7971636c6f75642e636f6d2f696d6167652f32303230303430312f746d69633963726a76712e706e67)
> 
> 图片无法访问[点击这里](https://imgservices-1252317822.file.myqcloud.com/image/20200401/tmic9crjvq.png)
> 
> 本题不需要考虑视觉还原，主要是布局效果实现。
> 
> 请附上对应的CSS代码，注意缩进和代码高亮，可以使用以下语法进行高亮：
> 
> html
> <div class="box">
        <div class="arrow">&lt;</div>
        <div class="wrap">
            <div class="day">2020年1月-3月</div>
            <div class="day">2020年4月-6月</div>
            <div class="day">2020年度OKR</div>
        </div>
        <div class="arrow">&gt;</div>
    </div>
> ```
> ```css
> .box{
            width: 60%;
            height: : 200px;
            border: 1px solid;
            line-height: 40px;
            margin: 30px auto;
            text-align: center;
            display: flex;
            flex-wrap: nowrap;
            flex-direction: row;
        }
        .wrap{
            width:90%;
            display: flex;
            flex-wrap: wrap;
            flex-direction: row;
            height: 42px;
            overflow: hidden;
        }
        .arrow{
            width: 5%;
            height: 40px;
            border:1px solid red;
            margin: 0 10px;
        }
        .day{
            border: 1px solid blue;
            flex-grow: 1;
        }
> ```
> 本期小测需要提供在线演示，不要参考别人的回答，诚实守信。
> 
> 本期小测无直播答疑，但是会总结要点。
> 
> 感谢您的参与！



> 实现一个有些挑战的布局：
> 
> ![](https://camo.githubusercontent.com/b93a3faa6d59dae0460befb63107f40ac9d8c7ee/68747470733a2f2f696d6773657276696365732d313235323331373832322e66696c652e6d7971636c6f75642e636f6d2f696d6167652f32303230303430312f746d69633963726a76712e706e67)
> 
> 图片无法访问[点击这里](https://imgservices-1252317822.file.myqcloud.com/image/20200401/tmic9crjvq.png)
> 
> 本题不需要考虑视觉还原，主要是布局效果实现。
> 
> 请附上对应的CSS代码，注意缩进和代码高亮，可以使用以下语法进行高亮：
> 
> html
> 你的代码在这里
> ```
> ```css
> 你的代码在这里
> ```
> 本期小测需要提供在线演示，不要参考别人的回答，诚实守信。
> 
> 本期小测无直播答疑，但是会总结要点。
> 
> 感谢您的参与！

**Comment by liyongleihf2006** [comment]
我思考了好久,我的想法跟@livetune的实现是一样的，但一直没有解决掉只有两行的情况下如何还能保证中件行还是在中间的问题,最终代码还是没有实现出来,学习了学习了

**Comment by xxf1996** [comment]
[demo](https://codepen.io/xxf1996/pen/OJVepVX)

用的是`flex`布局的`auto-fill`，每项宽度目前是固定的；不知道需不需要支持按特定顺序逐渐显示？目前只是按元素的`DOM`顺序逐渐显示的。

```css
.container {
  display: grid;
  grid-template-columns: repeat(auto-fill, 200px);
  height: 30px;
  overflow-y: hidden;
}
.item {
  height: 30px;
  line-height: 30px;
  text-align: center;
}
.item:nth-of-type(1) {
  background-color: rgba(255, 0, 0, 0.1);
}
.item:nth-of-type(2) {
  background-color: rgba(0, 255, 0, 0.1);
}
.item:nth-of-type(3) {
  background-color: rgba(0, 0, 255, 0.1);
}
```

```html
<div class="container">
  <div class="item">1</div>
  <div class="item">2</div>
  <div class="item">3</div>
</div>
```

**Comment by ziven27** [comment]
[在线Demo CodePen](https://codepen.io/ziven27/pen/vYOqbpe?editors=1100)

```CSS
.box {
  font-size: 0;
  font-family: sans-serif;
  display: flex;
  justify-content: flex-end;
  white-space: nowrap;
}
.inner {
  display: flex;
  justify-content: flex-end;
  overflow: hidden;
  height: 32px;
  flex-wrap: wrap;
}
.item._f {
  border-radius: 3px 0 0 3px;
}
.item._l {
  border-radius: 0 3px 3px 0;
}
.item {
  height: 16px;
  font-size: 12px;
  display: inline-block;
  text-align: center;
  border: 1px solid #ddd;
  margin-right: -1px;
  padding: 7px 1em;
  text-decoration: none;
  color: #333;
  background-color: #ffffff;
}
a.item:hover {
  background-color: #f5f5f5;
}
.item._on {
  color: #4c5fe2;
}

```

```HTML
<section class="box">
  <div class="inner">
    <a class="item _f" href="##" title="prev">&lt;</a>
    <a class="item" href="##" title="2020年4月-6月">2020年4月-6月</a>
    <strong class="item _on">2020年1月-3月</strong>
    <a class="item" href="##" title="2020年度OKR">2020年度OKR</a>
  </div>
  <a class="item _l" href="##" title="next">&gt;</a>
</section>
```

**Comment by Valar103769** [comment]
[jsbin](https://jsbin.com/geculojugi/edit?html,css,output)

```html
<div class="flex items-center">
  <span>&lt; |</span>
  <ul class="flex list-none flex-1" >
    <li class="p-1 flex-1 text-center sm:hidden">2020年4月 - 6月</li>
    <li class="p-1 text-blue-400 flex-1 text-center">2020年1月 - 3月</li>
    <li class="p-1 flex-1 text-center md:hidden">2020年度OKR</li>
  </ul>
    <span>| &gt;</span>
</div>
```

```css
*{
  margin:0;
  padding:0;
}

.flex{
  display:flex
}

.items-center{
  align-items: center;
}

.list-none{
  list-style-type: none;
}

.p-1{
  padding: 0.25rem;
}

.text-blue-400{
  color: #63b3ed;
}

.flex-1{
  flex: 1 1 0%;
}
.text-center{
  text-align: center;
}


 
@media (min-width: 1280px) {
  .lg\:hidden { display:none }
}

@media (max-width: 767px) {
  .md\:hidden { display:none }
}
@media (max-width: 639px) {
  .sm\:hidden { display:none }
}
```
