### ISSUE TITLE
DOM基础测试48期

### ISSUE THREAD

**Issue by zhangxinxu** [zhangxinxu/quiz#78]
**移动端**，页面上A，B两个div元素，请实现：

拖拽A元素到B元素上，A元素append到B元素中。

-----------------------------

本题考点在于移动端的拖拽功能实现。大家提交回答的时候，注意缩进距离，起始位置从左边缘开始；另外，github自带代码高亮，所以请使用下面示意的格式。

<pre>```js
// 你的JS代码写在这里
 ```</pre>

**其他**
本期小测没有直播，也没有打分，但是会反馈要点。

**Comment by LuckyRabbitFeet** [comment]
```html
<div id="box"></div>
<div id="item" draggable="true"></div>
```

```css
#box {
  width: 500px;
  height: 100px;
  background: red;
}

#item {
  width: 300px;
  height: 70px;
  background: cornflowerblue;
}
```

```js
let dragged
let box = document.getElementById('box')
let item = document.getElementById('item')

item.addEventListener("dragstart", function (event) {
  dragged = event.target
})

box.addEventListener("dragover", function (event) {
  event.preventDefault()
})

box.addEventListener("drop", function (event) {
  event.preventDefault()
  dragged.parentNode.removeChild(dragged)
  event.target.appendChild(dragged)
})
```

**Comment by liyongleihf2006** [comment]
[jsbin](https://jsbin.com/jigehut/edit?html,css,js)
```css
#draggable {
  width: 200px;
  height: 20px;
  text-align: center;
  background: white;
}

#dropzone {
  position: absolute;
  top: 300px;
  width: 200px;
  height: 20px;
  background: blueviolet;
  margin-bottom: 10px;
  padding: 10px;
}

.abs {
  position: absolute;
  z-index: 1;
}
```
```html
<div id="draggable" draggable="true">
  被拖拽的元素
</div>
<div id="dropzone"></div>
```
```js
var draggable = document.querySelector('#draggable')
var dropzone = document.querySelector('#dropzone')
var { width, height } = draggable.getBoundingClientRect()
var hasTouch = false
draggable.addEventListener('touchstart', touchstart)
document.addEventListener('touchmove', touchmove)
draggable.addEventListener('touchend', touchend)
draggable.addEventListener('touchcancel', reset)

function touchstart() {
  hasTouch = true
  draggable.classList.add('abs')
}
function touchmove(e) {
  if (hasTouch) {
    var touch = e.changedTouches[0]
    var pageX = touch.pageX
    var pageY = touch.pageY
    Object.assign(draggable.style, {
      left: pageX - width / 2 + 'px',
      top: pageY - height / 2 + 'px'
    })
  }
}
function touchend(e) {
  hasTouch = false
  var touch = e.changedTouches[0]
  var pageX = touch.pageX
  var pageY = touch.pageY
  var elements = document.elementsFromPoint(pageX, pageY)
  if (elements.includes(dropzone)) {
    dropzone.appendChild(draggable)
    draggable.removeEventListener('touchstart', touchstart)
    document.removeEventListener('touchmove', touchmove)
    draggable.removeEventListener('touchend', touchend)
    draggable.removeEventListener('touchcancel', reset)
  }
  reset()
}
function reset() {
  draggable.classList.remove('abs')
  Object.assign(draggable.style, {
    left: '',
    top: ''
  })
}
```

**Comment by xxf1996** [comment]
移动端可以使用touchEvent来处理拖拽操作；

[demo](https://codepen.io/xxf1996/full/WNQVKOj)

```html
<div id="t1">A</div>
<div id="t2">B</div>
```

```css
body {
  max-width: 400px;
}
#t1 {
  width: 100px;
  height: 100px;
  background-color: lightcoral;
}
#t2 {
  min-height: 200px;
  margin-top: 30px;
  background-color: lightcyan;
}
```

```js
const A = document.getElementById('t1')
const B = document.getElementById('t2')
let first = null

function start (e) {
  first = e.touches[0]
}

function move (e) {
  const cur = e.touches[0]
  if (first) {
    A.style.transform = `translate(${cur.pageX - first.pageX}px, ${cur.pageY - first.pageY}px)`
  }
}

function end (e) {
  const boxA = A.getBoundingClientRect()
  const boxB = B.getBoundingClientRect()

  if ( boxA.left > boxB.left
      && boxA.top > boxB.top
      && boxA.right < boxB.right
      && boxA.bottom < boxB.bottom ) { // 判断拖放停止的位置是否完全处于B之中
    A.removeEventListener('touchstart', start)
    A.removeEventListener('touchmove', move)
    A.removeEventListener('touchend', end)
    B.appendChild(A)
  }
  A.style.transform = 'none'
}

A.addEventListener('touchstart', start)
A.addEventListener('touchmove', move)
A.addEventListener('touchend', end)
```

**Comment by ziven27** [comment]
在线demo：[jsbin](https://output.jsbin.com/meqoluw)

```HTML
 <div draggable="true" class="ele" id="eleA"></div>
 <hr>  
 <div class="ele" id="eleB"></div>
```

```CSS
.ele{
  min-height: 100px;
  background-color:rgba(255,0,0,0.4);
  padding:8px;
}
```

```JS

var eleA=document.getElementById('eleA');
var eleB=document.getElementById('eleB');
var eleDrag=null;
eleA.addEventListener("dragstart", function(e) {
  eleDrag=e.target;
});
eleB.addEventListener("dragover", function(e) {
  e.preventDefault();
});
eleB.addEventListener("drop", function(e) {
  e.preventDefault();
  if(eleDrag===eleA && !eleB.contains(eleA)){
    e.target.appendChild(eleA);
  }
  eleDrag=null;
});
```
